services:
  - type: web
    name: inventario-cona
    env: python
    runtime: python-3.10.14
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000