services:
  - type: web
    name: inventario-cona
    env: python
    runtime: python-3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
